services:
  frontend:
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build:
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    networks:
      - app-net

networks:
  app-net:
