name: CI - Test Frontend & Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test -- --ci --watchAll=false

  backend:
    name: Backend Tests
    needs: frontend
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install
      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test
